# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iaMW2qNO1ULe7IvVwlixHN8obLnvJuw8

# **Function to estimate the value of cos(x) using a Taylor Series**


Taylor series of expansion can be used to estimate the cosine of any given value.....
The Taylor Series expansion for cos(x) is below.

cos(x)≈∑n=0∞(−1)nx2n(2n)!≈1−x22!+x44!−x66!+x88!−x1010! + ...

Now we will implement this using a function in Python
"""

import math

def func_cos(x, n):
    cos_approx = 0
    for i in range(n):
        coef = (-1)**i
        num = x**(2*i)
        denom = math.factorial(2*i)
        cos_approx += ( coef ) * ( (num)/(denom) )
    
    return cos_approx

angle_rad = (math.radians(45))
out = func_cos(angle_rad,5)
print("The estimated value using Taylor series is: ",out)

"""**Lets estimate the actual value of cos(45).....**"""

out = math.cos(angle_rad)
print("The actual value is: ",out)

"""**As we can see the estimated value is surprisingly close to the actual value.....This is just one use case of Taylor series Expansion, it can also be used to estimate the sine values as well as *e^x***"""